name: PHPUnit

on: [ push, pull_request ]

env:
  SWOOLE_VERSION: '4.5.3'
  SWOW_VERSION: 'develop'

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.0', '8.1', '8.2' ]
      max-parallel: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
          extensions: redis, pdo, pdo_mysql, bcmath, swoole
      - name: Setup Redis
        run: docker run --name redis -p 6379:6379 --restart always -d redis
      - name: Setup Packages
        run: composer update -o
      - name: Run Test Cases
        run: |
          composer analyse
          composer test
